defaults: &defaults
  working_directory: ~/working_directory
  steps:
    - checkout
    - run: composer install -n --prefer-dist
    - run: vendor/bin/security-checker security:check
    - run: vendor/bin/phpunit

version: 2
jobs:
  build-php56:
    <<: *defaults
    docker:
      - image: circleci/php:5.6
  build-php70:
    <<: *defaults
    docker:
      - image: circleci/php:7.0

workflows:
  version: 2
  build:
    jobs:
      - build-php56
      - build-php70
